default:
  image: maven:3.8.5-openjdk-11

variables:
  DB_HOSTNAME: "your_db_hostname"
  DB_NAME: "your_db_name"
  DB_USER: "your_db_user"
  DB_PASSWORD: "your_db_password"
  QUERIES: "artifact1=SELECT 1,artifact2=SELECT 2"

stages:
  - build_and_run

build_and_run_job:
  stage: build_and_run
  script:
    - echo "Building the project..."
    - mvn clean install
    - echo "Running the CSV exporter..."
    - java -cp target/csv-exporter-1.0-SNAPSHOT.jar com.gitlab.pipeline.CsvExporter
    - echo "Script finished."
  artifacts:
    paths:
      - target/*.csv
    when: on_success
